### ISSUE TITLE
Multiplication of messages after modification of node connected to relay-input

### ISSUE THREAD

**Issue by optys** [Onixarts/node-red-contrib-hapcan#47]
Version 2.4.1, node-red 1.2.9
After each modification of node (debug, function) connected to relay-input, one additional message is added.
After flows restart there is one message. After modification there are two messages. After another modification there are three messages and so on.
You need to modify name for example and deploy.
`[
    {
        "id": "351b9441.3d1f5c",
        "type": "relay-input",
        "z": "857384c7.aba8c8",
        "gateway": "31abcba8.62b1d4",
        "name": "Bistabilny 2",
        "group": 1,
        "node": "12",
        "channelFilter": 3,
        "userFieldStateON": "",
        "userFieldStateOFF": "",
        "x": 290,
        "y": 3260,
        "wires": [
            [
                "25ee1d25.ed6782"
            ]
        ]
    },
    {
        "id": "dd319d2b.cb0f6",
        "type": "relay-output",
        "z": "857384c7.aba8c8",
        "gateway": "31abcba8.62b1d4",
        "name": "Bistabilny 2",
        "group": 1,
        "node": "12",
        "channel": 1,
        "defaultAction": "2",
        "UNIV": 3,
        "x": 520,
        "y": 3200,
        "wires": []
    },
    {
        "id": "63cc03eb.68c46c",
        "type": "inject",
        "z": "857384c7.aba8c8",
        "name": "",
        "topic": "",
        "payload": "x",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 270,
        "y": 3200,
        "wires": [
            [
                "dd319d2b.cb0f6"
            ]
        ]
    },
    {
        "id": "25ee1d25.ed6782",
        "type": "debug",
        "z": "857384c7.aba8c8",
        "name": "d2",
        "active": true,
        "tosidebar": true,
        "console": true,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 490,
        "y": 3260,
        "wires": []
    },
    {
        "id": "31abcba8.62b1d4",
        "type": "hapcan-gateway",
        "z": "",
        "host": "192.168.10.10",
        "port": "1002",
        "group": "1",
        "node": "1",
        "debugmode": false,
        "reconnectPeriod": "1000",
        "devices": [
            {
                "id": "0C01",
                "node": 12,
                "group": 1,
                "description": "Bistabilny 2\u0000\u0000\u0000\u0000",
                "descriptionFirstPart": true,
                "serialNumber": "0x00000C5D",
                "hardwareType": 12288,
                "hardwareTypeString": "UNIV 3",
                "hardwareVersion": 3,
                "applicationType": 2,
                "applicationTypeString": "Relay",
                "applicationTypeIcon": "fa-power-off",
                "applicationVersion": 4,
                "firmwareVersion": 2
            }
        ]
    }
]`

**Comment by Onixarts** [comment]
Did You find this happen in relay input only or some other nodes too?

**Comment by optys** [comment]
I just tested it with rgb-input. It behaves the same.

**Comment by Onixarts** [comment]
It looks like the problem exist when You deploy a flow or changed nodes only. I'm using full deploy so I didn't experience the problem.
